services:

  hotels:
    image: b4rbatos/hotels:0.0.2-SNAPSHOT
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - b4rbatos-network

  rooms:
    image: b4rbatos/rooms:0.0.2-SNAPSHOT
    mem_limit: 800m
    ports:
      - "8081:8081"
    networks:
      - b4rbatos-network

  reservations:
    image: b4rbatos/reservations:0.0.2-SNAPSHOT
    mem_limit: 800m
    ports:
      - "8082:8082"
    networks:
      - b4rbatos-network

networks:
  b4rbatos-network: